import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/app/contexts/UserContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "APS Issue Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="stylesheet" href="https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/style.min.css" type="text/css" />
        <script src="https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/viewer3D.min.js"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const originalConsoleError = console.error;
              console.error = function(...args) {
                const joinedArgs = args.map(a => typeof a === 'string' ? a : (a && a.message ? a.message : (a ? a.toString() : ''))).join(' ');
                if (joinedArgs.includes('Failed to fetch resource') || joinedArgs.includes('hammered.bump.png') || (args.length === 1 && args[0] === undefined)) {
                  return;
                }
                return originalConsoleError.apply(console, args);
              };
              if (typeof window !== 'undefined') {
                window.addEventListener('error', function(event) {
                  const msg = event.message || '';
                  if (msg.includes('hammered.bump.png') || msg.includes('Failed to fetch resource') || event.error === undefined) {
                    event.stopImmediatePropagation();
                    event.preventDefault();
                  }
                }, true);

                window.addEventListener('unhandledrejection', function(event) {
                  const reason = event.reason;
                  const msg = reason ? (reason.message || reason.toString()) : '';
                  if (msg.includes('hammered.bump.png') || msg.includes('Failed to fetch resource') || reason === undefined) {
                    event.stopImmediatePropagation();
                    event.preventDefault();
                  }
                }, true);
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
